### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-bean-validation#22]
In general, it looks great (with some changes requested below). I didn't try running it as you've already had it tested etc. But I understood the guide just by reading it which is nice. :) When the things below are addressed, I'm happy for it to be published.

An issue I think should be addressed:

- [x] "Apply the following constraints:" I think this should say "The Astronaut class has the following constraints applied:" (otherwise it looks like the reader needs to add the annotations when they're already in the code snippet they've already copied. And in each of the bullet points, the last sentence would be eg "The annotation is applied to the `name` field." or "The annotation is on the `name` field.".

"place the annotation on the field value itself" -> "the annotation is on the field value itself"

And so on for the other descriptions of annotations added to fields in the example class code.

(I'm suspecting this might have been made more active in one of the reviews but, as this is a guide which is giving example code and then explaining what the code does, rather than instructions for the user to step through, I don't think the imperative/instructional voice is appropriate - it's potentially confusing to the reader whether they need to do anything other than copy the snippets and learn how they work. This needs to be distinguishable from actual actions they have to do, like create the class and copy the content into it.)

I think it's fine to be instructional here, for example "Now, write automated tests to drive the previously created service. Create the test class in the src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java file:" because they're expected to do something to make that happen. But the explanations below the snippet of the test class need to be explanatory, not instructional.

Happy to help if there's any questions.

Minor things:

- [x] "bean validation" should be lower-case when talking about the concept and only use upper-case when specifically mentioning the feature/spec name. eg "You will learn the basics of writing and testing a microservice that uses bean validation and the new functionality of Bean Validation 2.0. The service uses bean validation to validate that the supplied JavaBeans meet the defined constraints."

- [x] "click the Try it out button" - if it's an actual button to click (and the label makes it obvious where to click), just say "click **Try it out**".

- [x] "Copy the following into the text box:" -> "Copy the following example input into the text box:" (if that's what it is, or "value" as it says in the next paragraph - say what it is not just "the following").

- [x] "Click Execute" - highlight the button name with bold not monospace. Also, is the 'Execute' label our label or something that comes with Java EE? If we do it, can we change it to 'Run'?

- [x] "you will receive the response" "This time you will receive" - make present tense (it's describing how it works)

- [x] "since" -> "because" (only "since" when you're talking about time - it can be confusing when English is second lang.)

- [x] "Open Liberty server." - should end in colon (:) not full-stop/period (.) to lead into the snippet. (I realise I'm being really picky now but it's true... :) )

**Comment by alexsm82** [comment]
Regarding the comment " Also, is the 'Execute' label our label or something that comes with Java EE? If we do it, can we change it to 'Run'?", the execute button comes from the OpenAPI page so it is out of our control.

**Comment by evelinec** [comment]
About this comment: "The annotation is applied to the name field." or "The annotation is on the name field.". I think the later is a prefer option in terms of ID. I see in the latest PR #23, there are lots of sentences being changed to use passive voice. Will request ID team to take a look at this PR.

**Comment by evelinec** [comment]
@lauracowen can we close this issue? Thanks.
